AC_INIT([gratze], 
        [0.1], 
        [craig@postincrement.com],
        [gratze-tar.gz], 
        [http://www.postincrement.com])

AM_INIT_AUTOMAKE

# Force autoconf to be at least this version number:
AC_PREREQ([2.68])

AC_PROG_CXX

AC_CONFIG_FILES([Makefile])
AC_CONFIG_SUBDIRS(common disk emulator)
AC_OUTPUT
