#SDL_DIR =  `pwd`/SDL2-2.0.10/x86_64-w64-mingw32/
SDL_DIR =  ./SDL2-2.0.10/i686-w64-mingw32


#CXX = i686-w64-mingw32-g++
#CC  = i686-w64-mingw32-gcc
CXX=@CXX@
CC=@CC@

NFD_BUILD_TYPE=@NFD_BUILD_TYPE@
NFD_BUILD_ENV=@NFD_BUILD_ENV@
NFD_BUILD_DIR=@NFD_BUILD_DIR@

#SDL_LIBS = $(shell $(SDL_DIR)/bin/sdl2-config --libs)
SDL_LIBS=-lSDL2main -lSDL2

#CXXFLAGS += -I$(SDL_DIR)/include -I$(NFD_DIR)/src/include -std=c++17 -Wno-register -g -DEXECZ80 
#CFLAGS += -g -DLSB_FIRST -DDEBUG -DEXECZ80 
CXXFLAGS=@CXXFLAGS@
CFLAGS=@CFLAGS@

LDFLAGS += @LDFLAGS@ 
LDLIBS = @LDLIBS@  
LINK.o = $(LINK.cc)

vpath %.c mfz80

gratze:	main.o cassette.o Z80.o sdl_video.o emulator.o trs80.o Debug.o fdc.o $(NFD_LIB)
	$(CXX) $(LDFLAGS) -o $@ $^ $(LDLIBS)

main.o:	main.cc Makefile trs80.h emulator.h fdc.h options.h cassette.h

Z80.o: mfz80/Z80.c Makefile

debug.o: mfz80/debug.c

sdl_video.o: sdl_video.cc

emulator.o: emulator.cc emulator.h fdc.h options.h cassette.h

trs80.o: trs80.cc trs80.h fdc.h emulator.h options.h cassette.h

trs80.cc: $(NFD_LIB)

fdc.o: fdc.cc fdc.h options.h

cassette.o: cassette.cc cassette.h

clean:
	rm -f gratze *.o

$(NFD_LIB): nativefiledialog
	cd nativefiledialog/build/$(NFD_BUILD_DIR) && $(NFD_BUILD_ENV) sh -c "make config=$(NFD_BUILD_TYPE) clean ; make config=$(NFD_BUILD_TYPE)"

nfd: 
	cd nativefiledialog/build/$(NFD_BUILD_DIR) && $(NFD_BUILD_ENV) sh -c "make config=$(NFD_BUILD_TYPE) clean ; make config=$(NFD_BUILD_TYPE)"

nativefiledialog:
	git clone https://github.com/postincrement/nativefiledialog.git
	#git clone https://github.com/mlabbe/nativefiledialog.git
